{{- if .Values.sonarCR.create -}}
apiVersion: v2.edp.epam.com/v1
kind: Sonar
metadata:
  name: sonar
spec:
  defaultPermissionTemplate: edp-default
  edpSpec:
    dnsWildcard: {{ .Values.global.dnsWildCard }}
  basePath: "{{.Values.sonar.basePath}}"
{{ end }}
