{{- if .Values.sonar.deploy -}}
apiVersion: v2.edp.epam.com/v1alpha1
kind: Sonar
metadata:
  name: sonar
spec:
  edpSpec:
    dnsWildcard: {{ .Values.global.dnsWildCard }}
  type: Sonar
  initImage: {{.Values.sonar.initImage}}
  dbImage: {{.Values.sonar.dbImage}}
  image: {{.Values.sonar.image}}
  version: {{.Values.sonar.version}}
  basePath: "{{.Values.sonar.basePath}}"
  {{- if .Values.sonar.imagePullSecrets}}
  imagePullSecrets:
    {{- range .Values.sonar.imagePullSecrets }}
    - {{. -}}
    {{- end -}}
  {{end}}
  volumes:
    - capacity: {{ .Values.sonar.storage.data.size }}
      name: data
      storage_class: {{ .Values.sonar.storage.data.class }}
    - capacity: {{ .Values.sonar.storage.database.size }}
      name: db
      storage_class: {{ .Values.sonar.storage.database.class }}
{{end}}