all: true
dir: '{{.InterfaceDir}}/mocks'
structname: Mock{{.InterfaceName}}
pkgname: mocks
template: testify
filename: "{{ .InterfaceName | snakecase }}_generated.mock.go"
template-data:
  unroll-variadic: true
packages:
  github.com/epam/edp-sonar-operator/pkg/client/sonar:
    interfaces:
      ClientInterface:
