with-expecter: True
inpackage: False
dir: "{{.InterfaceDir}}/mocks"
mockname: "Mock{{.InterfaceName}}"
outpkg: "mocks"
filename: "{{.InterfaceName | lower}}_mock.go"
issue-845-fix: True
resolve-type-alias: false
disable-version-string: true
packages:
  github.com/epam/edp-sonar-operator/pkg/client/sonar:
    interfaces:
      ClientInterface:
