apiVersion: edp.epam.com/v1alpha1
kind: Sonar
metadata:
  name: sonar
spec:
  url: https://sonar.com
  secret: sonar-admin
  defaultPermissionTemplate: test
  settings:
    - key: sonar.global.exclusions
      values:
        - "**/*.jsx"
        - "**/*.tsx"
    - key: sonar.issue.ignore.block
      fieldValues:
          beginBlockRegexp: ".*"
          endBlockRegexp: ".*"
    - key: sonar.dbcleaner.hoursBeforeKeepingOnlyOneSnapshotByDay
      value: "20"
    - key: email.smtp_password.secured
      valueRef:
        secretKeyRef:
          key: password
          name: sonar-smtp


---
apiVersion: v1
kind: Secret
metadata:
  name: sonar-admin
data:
  user: YWRtaW4=
  password: YWRtaW4x

---
apiVersion: v1
kind: Secret
metadata:
  name: sonar-smtp
data:
  password: c29uYXItcGFzc3dvcmQ=
