// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/epam/edp-sonar-operator/pkg/client/sonar"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGroupInterface creates a new instance of MockGroupInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroupInterface {
	mock := &MockGroupInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGroupInterface is an autogenerated mock type for the GroupInterface type
type MockGroupInterface struct {
	mock.Mock
}

type MockGroupInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupInterface) EXPECT() *MockGroupInterface_Expecter {
	return &MockGroupInterface_Expecter{mock: &_m.Mock}
}

// AddPermissionsToGroup provides a mock function for the type MockGroupInterface
func (_mock *MockGroupInterface) AddPermissionsToGroup(groupName string, permissions string) error {
	ret := _mock.Called(groupName, permissions)

	if len(ret) == 0 {
		panic("no return value specified for AddPermissionsToGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(groupName, permissions)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGroupInterface_AddPermissionsToGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPermissionsToGroup'
type MockGroupInterface_AddPermissionsToGroup_Call struct {
	*mock.Call
}

// AddPermissionsToGroup is a helper method to define mock.On call
//   - groupName string
//   - permissions string
func (_e *MockGroupInterface_Expecter) AddPermissionsToGroup(groupName interface{}, permissions interface{}) *MockGroupInterface_AddPermissionsToGroup_Call {
	return &MockGroupInterface_AddPermissionsToGroup_Call{Call: _e.mock.On("AddPermissionsToGroup", groupName, permissions)}
}

func (_c *MockGroupInterface_AddPermissionsToGroup_Call) Run(run func(groupName string, permissions string)) *MockGroupInterface_AddPermissionsToGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupInterface_AddPermissionsToGroup_Call) Return(err error) *MockGroupInterface_AddPermissionsToGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGroupInterface_AddPermissionsToGroup_Call) RunAndReturn(run func(groupName string, permissions string) error) *MockGroupInterface_AddPermissionsToGroup_Call {
	_c.Call.Return(run)
	return _c
}

// AddUserToGroup provides a mock function for the type MockGroupInterface
func (_mock *MockGroupInterface) AddUserToGroup(ctx context.Context, userLogin string, groupName string) error {
	ret := _mock.Called(ctx, userLogin, groupName)

	if len(ret) == 0 {
		panic("no return value specified for AddUserToGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userLogin, groupName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGroupInterface_AddUserToGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUserToGroup'
type MockGroupInterface_AddUserToGroup_Call struct {
	*mock.Call
}

// AddUserToGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - userLogin string
//   - groupName string
func (_e *MockGroupInterface_Expecter) AddUserToGroup(ctx interface{}, userLogin interface{}, groupName interface{}) *MockGroupInterface_AddUserToGroup_Call {
	return &MockGroupInterface_AddUserToGroup_Call{Call: _e.mock.On("AddUserToGroup", ctx, userLogin, groupName)}
}

func (_c *MockGroupInterface_AddUserToGroup_Call) Run(run func(ctx context.Context, userLogin string, groupName string)) *MockGroupInterface_AddUserToGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGroupInterface_AddUserToGroup_Call) Return(err error) *MockGroupInterface_AddUserToGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGroupInterface_AddUserToGroup_Call) RunAndReturn(run func(ctx context.Context, userLogin string, groupName string) error) *MockGroupInterface_AddUserToGroup_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGroup provides a mock function for the type MockGroupInterface
func (_mock *MockGroupInterface) CreateGroup(ctx context.Context, gr *sonar.Group) error {
	ret := _mock.Called(ctx, gr)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sonar.Group) error); ok {
		r0 = returnFunc(ctx, gr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGroupInterface_CreateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroup'
type MockGroupInterface_CreateGroup_Call struct {
	*mock.Call
}

// CreateGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - gr *sonar.Group
func (_e *MockGroupInterface_Expecter) CreateGroup(ctx interface{}, gr interface{}) *MockGroupInterface_CreateGroup_Call {
	return &MockGroupInterface_CreateGroup_Call{Call: _e.mock.On("CreateGroup", ctx, gr)}
}

func (_c *MockGroupInterface_CreateGroup_Call) Run(run func(ctx context.Context, gr *sonar.Group)) *MockGroupInterface_CreateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sonar.Group
		if args[1] != nil {
			arg1 = args[1].(*sonar.Group)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupInterface_CreateGroup_Call) Return(err error) *MockGroupInterface_CreateGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGroupInterface_CreateGroup_Call) RunAndReturn(run func(ctx context.Context, gr *sonar.Group) error) *MockGroupInterface_CreateGroup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteGroup provides a mock function for the type MockGroupInterface
func (_mock *MockGroupInterface) DeleteGroup(ctx context.Context, groupName string) error {
	ret := _mock.Called(ctx, groupName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, groupName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGroupInterface_DeleteGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteGroup'
type MockGroupInterface_DeleteGroup_Call struct {
	*mock.Call
}

// DeleteGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - groupName string
func (_e *MockGroupInterface_Expecter) DeleteGroup(ctx interface{}, groupName interface{}) *MockGroupInterface_DeleteGroup_Call {
	return &MockGroupInterface_DeleteGroup_Call{Call: _e.mock.On("DeleteGroup", ctx, groupName)}
}

func (_c *MockGroupInterface_DeleteGroup_Call) Run(run func(ctx context.Context, groupName string)) *MockGroupInterface_DeleteGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupInterface_DeleteGroup_Call) Return(err error) *MockGroupInterface_DeleteGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGroupInterface_DeleteGroup_Call) RunAndReturn(run func(ctx context.Context, groupName string) error) *MockGroupInterface_DeleteGroup_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroup provides a mock function for the type MockGroupInterface
func (_mock *MockGroupInterface) GetGroup(ctx context.Context, groupName string) (*sonar.Group, error) {
	ret := _mock.Called(ctx, groupName)

	if len(ret) == 0 {
		panic("no return value specified for GetGroup")
	}

	var r0 *sonar.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*sonar.Group, error)); ok {
		return returnFunc(ctx, groupName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *sonar.Group); ok {
		r0 = returnFunc(ctx, groupName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sonar.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, groupName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupInterface_GetGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroup'
type MockGroupInterface_GetGroup_Call struct {
	*mock.Call
}

// GetGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - groupName string
func (_e *MockGroupInterface_Expecter) GetGroup(ctx interface{}, groupName interface{}) *MockGroupInterface_GetGroup_Call {
	return &MockGroupInterface_GetGroup_Call{Call: _e.mock.On("GetGroup", ctx, groupName)}
}

func (_c *MockGroupInterface_GetGroup_Call) Run(run func(ctx context.Context, groupName string)) *MockGroupInterface_GetGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupInterface_GetGroup_Call) Return(group *sonar.Group, err error) *MockGroupInterface_GetGroup_Call {
	_c.Call.Return(group, err)
	return _c
}

func (_c *MockGroupInterface_GetGroup_Call) RunAndReturn(run func(ctx context.Context, groupName string) (*sonar.Group, error)) *MockGroupInterface_GetGroup_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveUserFromGroup provides a mock function for the type MockGroupInterface
func (_mock *MockGroupInterface) RemoveUserFromGroup(ctx context.Context, userLogin string, groupName string) error {
	ret := _mock.Called(ctx, userLogin, groupName)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUserFromGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userLogin, groupName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGroupInterface_RemoveUserFromGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUserFromGroup'
type MockGroupInterface_RemoveUserFromGroup_Call struct {
	*mock.Call
}

// RemoveUserFromGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - userLogin string
//   - groupName string
func (_e *MockGroupInterface_Expecter) RemoveUserFromGroup(ctx interface{}, userLogin interface{}, groupName interface{}) *MockGroupInterface_RemoveUserFromGroup_Call {
	return &MockGroupInterface_RemoveUserFromGroup_Call{Call: _e.mock.On("RemoveUserFromGroup", ctx, userLogin, groupName)}
}

func (_c *MockGroupInterface_RemoveUserFromGroup_Call) Run(run func(ctx context.Context, userLogin string, groupName string)) *MockGroupInterface_RemoveUserFromGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGroupInterface_RemoveUserFromGroup_Call) Return(err error) *MockGroupInterface_RemoveUserFromGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGroupInterface_RemoveUserFromGroup_Call) RunAndReturn(run func(ctx context.Context, userLogin string, groupName string) error) *MockGroupInterface_RemoveUserFromGroup_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGroup provides a mock function for the type MockGroupInterface
func (_mock *MockGroupInterface) UpdateGroup(ctx context.Context, currentName string, group *sonar.Group) error {
	ret := _mock.Called(ctx, currentName, group)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *sonar.Group) error); ok {
		r0 = returnFunc(ctx, currentName, group)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGroupInterface_UpdateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGroup'
type MockGroupInterface_UpdateGroup_Call struct {
	*mock.Call
}

// UpdateGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - currentName string
//   - group *sonar.Group
func (_e *MockGroupInterface_Expecter) UpdateGroup(ctx interface{}, currentName interface{}, group interface{}) *MockGroupInterface_UpdateGroup_Call {
	return &MockGroupInterface_UpdateGroup_Call{Call: _e.mock.On("UpdateGroup", ctx, currentName, group)}
}

func (_c *MockGroupInterface_UpdateGroup_Call) Run(run func(ctx context.Context, currentName string, group *sonar.Group)) *MockGroupInterface_UpdateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *sonar.Group
		if args[2] != nil {
			arg2 = args[2].(*sonar.Group)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGroupInterface_UpdateGroup_Call) Return(err error) *MockGroupInterface_UpdateGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGroupInterface_UpdateGroup_Call) RunAndReturn(run func(ctx context.Context, currentName string, group *sonar.Group) error) *MockGroupInterface_UpdateGroup_Call {
	_c.Call.Return(run)
	return _c
}
