// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/epam/edp-sonar-operator/pkg/client/sonar"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPermissionTemplateInterface creates a new instance of MockPermissionTemplateInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPermissionTemplateInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPermissionTemplateInterface {
	mock := &MockPermissionTemplateInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPermissionTemplateInterface is an autogenerated mock type for the PermissionTemplateInterface type
type MockPermissionTemplateInterface struct {
	mock.Mock
}

type MockPermissionTemplateInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPermissionTemplateInterface) EXPECT() *MockPermissionTemplateInterface_Expecter {
	return &MockPermissionTemplateInterface_Expecter{mock: &_m.Mock}
}

// AddGroupToPermissionTemplate provides a mock function for the type MockPermissionTemplateInterface
func (_mock *MockPermissionTemplateInterface) AddGroupToPermissionTemplate(ctx context.Context, templateID string, groupName string, permission string) error {
	ret := _mock.Called(ctx, templateID, groupName, permission)

	if len(ret) == 0 {
		panic("no return value specified for AddGroupToPermissionTemplate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, templateID, groupName, permission)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPermissionTemplateInterface_AddGroupToPermissionTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddGroupToPermissionTemplate'
type MockPermissionTemplateInterface_AddGroupToPermissionTemplate_Call struct {
	*mock.Call
}

// AddGroupToPermissionTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - templateID string
//   - groupName string
//   - permission string
func (_e *MockPermissionTemplateInterface_Expecter) AddGroupToPermissionTemplate(ctx interface{}, templateID interface{}, groupName interface{}, permission interface{}) *MockPermissionTemplateInterface_AddGroupToPermissionTemplate_Call {
	return &MockPermissionTemplateInterface_AddGroupToPermissionTemplate_Call{Call: _e.mock.On("AddGroupToPermissionTemplate", ctx, templateID, groupName, permission)}
}

func (_c *MockPermissionTemplateInterface_AddGroupToPermissionTemplate_Call) Run(run func(ctx context.Context, templateID string, groupName string, permission string)) *MockPermissionTemplateInterface_AddGroupToPermissionTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPermissionTemplateInterface_AddGroupToPermissionTemplate_Call) Return(err error) *MockPermissionTemplateInterface_AddGroupToPermissionTemplate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPermissionTemplateInterface_AddGroupToPermissionTemplate_Call) RunAndReturn(run func(ctx context.Context, templateID string, groupName string, permission string) error) *MockPermissionTemplateInterface_AddGroupToPermissionTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// AddPermissionToGroup provides a mock function for the type MockPermissionTemplateInterface
func (_mock *MockPermissionTemplateInterface) AddPermissionToGroup(ctx context.Context, groupName string, permission string) error {
	ret := _mock.Called(ctx, groupName, permission)

	if len(ret) == 0 {
		panic("no return value specified for AddPermissionToGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, groupName, permission)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPermissionTemplateInterface_AddPermissionToGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPermissionToGroup'
type MockPermissionTemplateInterface_AddPermissionToGroup_Call struct {
	*mock.Call
}

// AddPermissionToGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - groupName string
//   - permission string
func (_e *MockPermissionTemplateInterface_Expecter) AddPermissionToGroup(ctx interface{}, groupName interface{}, permission interface{}) *MockPermissionTemplateInterface_AddPermissionToGroup_Call {
	return &MockPermissionTemplateInterface_AddPermissionToGroup_Call{Call: _e.mock.On("AddPermissionToGroup", ctx, groupName, permission)}
}

func (_c *MockPermissionTemplateInterface_AddPermissionToGroup_Call) Run(run func(ctx context.Context, groupName string, permission string)) *MockPermissionTemplateInterface_AddPermissionToGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPermissionTemplateInterface_AddPermissionToGroup_Call) Return(err error) *MockPermissionTemplateInterface_AddPermissionToGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPermissionTemplateInterface_AddPermissionToGroup_Call) RunAndReturn(run func(ctx context.Context, groupName string, permission string) error) *MockPermissionTemplateInterface_AddPermissionToGroup_Call {
	_c.Call.Return(run)
	return _c
}

// AddPermissionToUser provides a mock function for the type MockPermissionTemplateInterface
func (_mock *MockPermissionTemplateInterface) AddPermissionToUser(ctx context.Context, userLogin string, permission string) error {
	ret := _mock.Called(ctx, userLogin, permission)

	if len(ret) == 0 {
		panic("no return value specified for AddPermissionToUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userLogin, permission)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPermissionTemplateInterface_AddPermissionToUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPermissionToUser'
type MockPermissionTemplateInterface_AddPermissionToUser_Call struct {
	*mock.Call
}

// AddPermissionToUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userLogin string
//   - permission string
func (_e *MockPermissionTemplateInterface_Expecter) AddPermissionToUser(ctx interface{}, userLogin interface{}, permission interface{}) *MockPermissionTemplateInterface_AddPermissionToUser_Call {
	return &MockPermissionTemplateInterface_AddPermissionToUser_Call{Call: _e.mock.On("AddPermissionToUser", ctx, userLogin, permission)}
}

func (_c *MockPermissionTemplateInterface_AddPermissionToUser_Call) Run(run func(ctx context.Context, userLogin string, permission string)) *MockPermissionTemplateInterface_AddPermissionToUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPermissionTemplateInterface_AddPermissionToUser_Call) Return(err error) *MockPermissionTemplateInterface_AddPermissionToUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPermissionTemplateInterface_AddPermissionToUser_Call) RunAndReturn(run func(ctx context.Context, userLogin string, permission string) error) *MockPermissionTemplateInterface_AddPermissionToUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePermissionTemplate provides a mock function for the type MockPermissionTemplateInterface
func (_mock *MockPermissionTemplateInterface) CreatePermissionTemplate(ctx context.Context, tpl *sonar.PermissionTemplateData) (*sonar.PermissionTemplate, error) {
	ret := _mock.Called(ctx, tpl)

	if len(ret) == 0 {
		panic("no return value specified for CreatePermissionTemplate")
	}

	var r0 *sonar.PermissionTemplate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sonar.PermissionTemplateData) (*sonar.PermissionTemplate, error)); ok {
		return returnFunc(ctx, tpl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sonar.PermissionTemplateData) *sonar.PermissionTemplate); ok {
		r0 = returnFunc(ctx, tpl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sonar.PermissionTemplate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sonar.PermissionTemplateData) error); ok {
		r1 = returnFunc(ctx, tpl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPermissionTemplateInterface_CreatePermissionTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePermissionTemplate'
type MockPermissionTemplateInterface_CreatePermissionTemplate_Call struct {
	*mock.Call
}

// CreatePermissionTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - tpl *sonar.PermissionTemplateData
func (_e *MockPermissionTemplateInterface_Expecter) CreatePermissionTemplate(ctx interface{}, tpl interface{}) *MockPermissionTemplateInterface_CreatePermissionTemplate_Call {
	return &MockPermissionTemplateInterface_CreatePermissionTemplate_Call{Call: _e.mock.On("CreatePermissionTemplate", ctx, tpl)}
}

func (_c *MockPermissionTemplateInterface_CreatePermissionTemplate_Call) Run(run func(ctx context.Context, tpl *sonar.PermissionTemplateData)) *MockPermissionTemplateInterface_CreatePermissionTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sonar.PermissionTemplateData
		if args[1] != nil {
			arg1 = args[1].(*sonar.PermissionTemplateData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPermissionTemplateInterface_CreatePermissionTemplate_Call) Return(permissionTemplate *sonar.PermissionTemplate, err error) *MockPermissionTemplateInterface_CreatePermissionTemplate_Call {
	_c.Call.Return(permissionTemplate, err)
	return _c
}

func (_c *MockPermissionTemplateInterface_CreatePermissionTemplate_Call) RunAndReturn(run func(ctx context.Context, tpl *sonar.PermissionTemplateData) (*sonar.PermissionTemplate, error)) *MockPermissionTemplateInterface_CreatePermissionTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePermissionTemplate provides a mock function for the type MockPermissionTemplateInterface
func (_mock *MockPermissionTemplateInterface) DeletePermissionTemplate(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePermissionTemplate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPermissionTemplateInterface_DeletePermissionTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePermissionTemplate'
type MockPermissionTemplateInterface_DeletePermissionTemplate_Call struct {
	*mock.Call
}

// DeletePermissionTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockPermissionTemplateInterface_Expecter) DeletePermissionTemplate(ctx interface{}, id interface{}) *MockPermissionTemplateInterface_DeletePermissionTemplate_Call {
	return &MockPermissionTemplateInterface_DeletePermissionTemplate_Call{Call: _e.mock.On("DeletePermissionTemplate", ctx, id)}
}

func (_c *MockPermissionTemplateInterface_DeletePermissionTemplate_Call) Run(run func(ctx context.Context, id string)) *MockPermissionTemplateInterface_DeletePermissionTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPermissionTemplateInterface_DeletePermissionTemplate_Call) Return(err error) *MockPermissionTemplateInterface_DeletePermissionTemplate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPermissionTemplateInterface_DeletePermissionTemplate_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockPermissionTemplateInterface_DeletePermissionTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupPermissions provides a mock function for the type MockPermissionTemplateInterface
func (_mock *MockPermissionTemplateInterface) GetGroupPermissions(ctx context.Context, groupName string) ([]string, error) {
	ret := _mock.Called(ctx, groupName)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupPermissions")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, groupName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, groupName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, groupName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPermissionTemplateInterface_GetGroupPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupPermissions'
type MockPermissionTemplateInterface_GetGroupPermissions_Call struct {
	*mock.Call
}

// GetGroupPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - groupName string
func (_e *MockPermissionTemplateInterface_Expecter) GetGroupPermissions(ctx interface{}, groupName interface{}) *MockPermissionTemplateInterface_GetGroupPermissions_Call {
	return &MockPermissionTemplateInterface_GetGroupPermissions_Call{Call: _e.mock.On("GetGroupPermissions", ctx, groupName)}
}

func (_c *MockPermissionTemplateInterface_GetGroupPermissions_Call) Run(run func(ctx context.Context, groupName string)) *MockPermissionTemplateInterface_GetGroupPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPermissionTemplateInterface_GetGroupPermissions_Call) Return(strings []string, err error) *MockPermissionTemplateInterface_GetGroupPermissions_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockPermissionTemplateInterface_GetGroupPermissions_Call) RunAndReturn(run func(ctx context.Context, groupName string) ([]string, error)) *MockPermissionTemplateInterface_GetGroupPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// GetPermissionTemplate provides a mock function for the type MockPermissionTemplateInterface
func (_mock *MockPermissionTemplateInterface) GetPermissionTemplate(ctx context.Context, name string) (*sonar.PermissionTemplate, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissionTemplate")
	}

	var r0 *sonar.PermissionTemplate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*sonar.PermissionTemplate, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *sonar.PermissionTemplate); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sonar.PermissionTemplate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPermissionTemplateInterface_GetPermissionTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermissionTemplate'
type MockPermissionTemplateInterface_GetPermissionTemplate_Call struct {
	*mock.Call
}

// GetPermissionTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockPermissionTemplateInterface_Expecter) GetPermissionTemplate(ctx interface{}, name interface{}) *MockPermissionTemplateInterface_GetPermissionTemplate_Call {
	return &MockPermissionTemplateInterface_GetPermissionTemplate_Call{Call: _e.mock.On("GetPermissionTemplate", ctx, name)}
}

func (_c *MockPermissionTemplateInterface_GetPermissionTemplate_Call) Run(run func(ctx context.Context, name string)) *MockPermissionTemplateInterface_GetPermissionTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPermissionTemplateInterface_GetPermissionTemplate_Call) Return(permissionTemplate *sonar.PermissionTemplate, err error) *MockPermissionTemplateInterface_GetPermissionTemplate_Call {
	_c.Call.Return(permissionTemplate, err)
	return _c
}

func (_c *MockPermissionTemplateInterface_GetPermissionTemplate_Call) RunAndReturn(run func(ctx context.Context, name string) (*sonar.PermissionTemplate, error)) *MockPermissionTemplateInterface_GetPermissionTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// GetPermissionTemplateGroups provides a mock function for the type MockPermissionTemplateInterface
func (_mock *MockPermissionTemplateInterface) GetPermissionTemplateGroups(ctx context.Context, templateID string) (map[string][]string, error) {
	ret := _mock.Called(ctx, templateID)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissionTemplateGroups")
	}

	var r0 map[string][]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (map[string][]string, error)); ok {
		return returnFunc(ctx, templateID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) map[string][]string); ok {
		r0 = returnFunc(ctx, templateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, templateID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPermissionTemplateInterface_GetPermissionTemplateGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermissionTemplateGroups'
type MockPermissionTemplateInterface_GetPermissionTemplateGroups_Call struct {
	*mock.Call
}

// GetPermissionTemplateGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - templateID string
func (_e *MockPermissionTemplateInterface_Expecter) GetPermissionTemplateGroups(ctx interface{}, templateID interface{}) *MockPermissionTemplateInterface_GetPermissionTemplateGroups_Call {
	return &MockPermissionTemplateInterface_GetPermissionTemplateGroups_Call{Call: _e.mock.On("GetPermissionTemplateGroups", ctx, templateID)}
}

func (_c *MockPermissionTemplateInterface_GetPermissionTemplateGroups_Call) Run(run func(ctx context.Context, templateID string)) *MockPermissionTemplateInterface_GetPermissionTemplateGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPermissionTemplateInterface_GetPermissionTemplateGroups_Call) Return(stringToStrings map[string][]string, err error) *MockPermissionTemplateInterface_GetPermissionTemplateGroups_Call {
	_c.Call.Return(stringToStrings, err)
	return _c
}

func (_c *MockPermissionTemplateInterface_GetPermissionTemplateGroups_Call) RunAndReturn(run func(ctx context.Context, templateID string) (map[string][]string, error)) *MockPermissionTemplateInterface_GetPermissionTemplateGroups_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserPermissions provides a mock function for the type MockPermissionTemplateInterface
func (_mock *MockPermissionTemplateInterface) GetUserPermissions(ctx context.Context, userLogin string) ([]string, error) {
	ret := _mock.Called(ctx, userLogin)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPermissions")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, userLogin)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, userLogin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userLogin)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPermissionTemplateInterface_GetUserPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserPermissions'
type MockPermissionTemplateInterface_GetUserPermissions_Call struct {
	*mock.Call
}

// GetUserPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - userLogin string
func (_e *MockPermissionTemplateInterface_Expecter) GetUserPermissions(ctx interface{}, userLogin interface{}) *MockPermissionTemplateInterface_GetUserPermissions_Call {
	return &MockPermissionTemplateInterface_GetUserPermissions_Call{Call: _e.mock.On("GetUserPermissions", ctx, userLogin)}
}

func (_c *MockPermissionTemplateInterface_GetUserPermissions_Call) Run(run func(ctx context.Context, userLogin string)) *MockPermissionTemplateInterface_GetUserPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPermissionTemplateInterface_GetUserPermissions_Call) Return(strings []string, err error) *MockPermissionTemplateInterface_GetUserPermissions_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockPermissionTemplateInterface_GetUserPermissions_Call) RunAndReturn(run func(ctx context.Context, userLogin string) ([]string, error)) *MockPermissionTemplateInterface_GetUserPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveGroupFromPermissionTemplate provides a mock function for the type MockPermissionTemplateInterface
func (_mock *MockPermissionTemplateInterface) RemoveGroupFromPermissionTemplate(ctx context.Context, templateID string, groupName string, permission string) error {
	ret := _mock.Called(ctx, templateID, groupName, permission)

	if len(ret) == 0 {
		panic("no return value specified for RemoveGroupFromPermissionTemplate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, templateID, groupName, permission)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPermissionTemplateInterface_RemoveGroupFromPermissionTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveGroupFromPermissionTemplate'
type MockPermissionTemplateInterface_RemoveGroupFromPermissionTemplate_Call struct {
	*mock.Call
}

// RemoveGroupFromPermissionTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - templateID string
//   - groupName string
//   - permission string
func (_e *MockPermissionTemplateInterface_Expecter) RemoveGroupFromPermissionTemplate(ctx interface{}, templateID interface{}, groupName interface{}, permission interface{}) *MockPermissionTemplateInterface_RemoveGroupFromPermissionTemplate_Call {
	return &MockPermissionTemplateInterface_RemoveGroupFromPermissionTemplate_Call{Call: _e.mock.On("RemoveGroupFromPermissionTemplate", ctx, templateID, groupName, permission)}
}

func (_c *MockPermissionTemplateInterface_RemoveGroupFromPermissionTemplate_Call) Run(run func(ctx context.Context, templateID string, groupName string, permission string)) *MockPermissionTemplateInterface_RemoveGroupFromPermissionTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPermissionTemplateInterface_RemoveGroupFromPermissionTemplate_Call) Return(err error) *MockPermissionTemplateInterface_RemoveGroupFromPermissionTemplate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPermissionTemplateInterface_RemoveGroupFromPermissionTemplate_Call) RunAndReturn(run func(ctx context.Context, templateID string, groupName string, permission string) error) *MockPermissionTemplateInterface_RemoveGroupFromPermissionTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// RemovePermissionFromGroup provides a mock function for the type MockPermissionTemplateInterface
func (_mock *MockPermissionTemplateInterface) RemovePermissionFromGroup(ctx context.Context, groupName string, permission string) error {
	ret := _mock.Called(ctx, groupName, permission)

	if len(ret) == 0 {
		panic("no return value specified for RemovePermissionFromGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, groupName, permission)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPermissionTemplateInterface_RemovePermissionFromGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePermissionFromGroup'
type MockPermissionTemplateInterface_RemovePermissionFromGroup_Call struct {
	*mock.Call
}

// RemovePermissionFromGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - groupName string
//   - permission string
func (_e *MockPermissionTemplateInterface_Expecter) RemovePermissionFromGroup(ctx interface{}, groupName interface{}, permission interface{}) *MockPermissionTemplateInterface_RemovePermissionFromGroup_Call {
	return &MockPermissionTemplateInterface_RemovePermissionFromGroup_Call{Call: _e.mock.On("RemovePermissionFromGroup", ctx, groupName, permission)}
}

func (_c *MockPermissionTemplateInterface_RemovePermissionFromGroup_Call) Run(run func(ctx context.Context, groupName string, permission string)) *MockPermissionTemplateInterface_RemovePermissionFromGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPermissionTemplateInterface_RemovePermissionFromGroup_Call) Return(err error) *MockPermissionTemplateInterface_RemovePermissionFromGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPermissionTemplateInterface_RemovePermissionFromGroup_Call) RunAndReturn(run func(ctx context.Context, groupName string, permission string) error) *MockPermissionTemplateInterface_RemovePermissionFromGroup_Call {
	_c.Call.Return(run)
	return _c
}

// RemovePermissionFromUser provides a mock function for the type MockPermissionTemplateInterface
func (_mock *MockPermissionTemplateInterface) RemovePermissionFromUser(ctx context.Context, userLogin string, permission string) error {
	ret := _mock.Called(ctx, userLogin, permission)

	if len(ret) == 0 {
		panic("no return value specified for RemovePermissionFromUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userLogin, permission)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPermissionTemplateInterface_RemovePermissionFromUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePermissionFromUser'
type MockPermissionTemplateInterface_RemovePermissionFromUser_Call struct {
	*mock.Call
}

// RemovePermissionFromUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userLogin string
//   - permission string
func (_e *MockPermissionTemplateInterface_Expecter) RemovePermissionFromUser(ctx interface{}, userLogin interface{}, permission interface{}) *MockPermissionTemplateInterface_RemovePermissionFromUser_Call {
	return &MockPermissionTemplateInterface_RemovePermissionFromUser_Call{Call: _e.mock.On("RemovePermissionFromUser", ctx, userLogin, permission)}
}

func (_c *MockPermissionTemplateInterface_RemovePermissionFromUser_Call) Run(run func(ctx context.Context, userLogin string, permission string)) *MockPermissionTemplateInterface_RemovePermissionFromUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPermissionTemplateInterface_RemovePermissionFromUser_Call) Return(err error) *MockPermissionTemplateInterface_RemovePermissionFromUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPermissionTemplateInterface_RemovePermissionFromUser_Call) RunAndReturn(run func(ctx context.Context, userLogin string, permission string) error) *MockPermissionTemplateInterface_RemovePermissionFromUser_Call {
	_c.Call.Return(run)
	return _c
}

// SetDefaultPermissionTemplate provides a mock function for the type MockPermissionTemplateInterface
func (_mock *MockPermissionTemplateInterface) SetDefaultPermissionTemplate(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for SetDefaultPermissionTemplate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPermissionTemplateInterface_SetDefaultPermissionTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDefaultPermissionTemplate'
type MockPermissionTemplateInterface_SetDefaultPermissionTemplate_Call struct {
	*mock.Call
}

// SetDefaultPermissionTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockPermissionTemplateInterface_Expecter) SetDefaultPermissionTemplate(ctx interface{}, name interface{}) *MockPermissionTemplateInterface_SetDefaultPermissionTemplate_Call {
	return &MockPermissionTemplateInterface_SetDefaultPermissionTemplate_Call{Call: _e.mock.On("SetDefaultPermissionTemplate", ctx, name)}
}

func (_c *MockPermissionTemplateInterface_SetDefaultPermissionTemplate_Call) Run(run func(ctx context.Context, name string)) *MockPermissionTemplateInterface_SetDefaultPermissionTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPermissionTemplateInterface_SetDefaultPermissionTemplate_Call) Return(err error) *MockPermissionTemplateInterface_SetDefaultPermissionTemplate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPermissionTemplateInterface_SetDefaultPermissionTemplate_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockPermissionTemplateInterface_SetDefaultPermissionTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePermissionTemplate provides a mock function for the type MockPermissionTemplateInterface
func (_mock *MockPermissionTemplateInterface) UpdatePermissionTemplate(ctx context.Context, tpl *sonar.PermissionTemplate) error {
	ret := _mock.Called(ctx, tpl)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePermissionTemplate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sonar.PermissionTemplate) error); ok {
		r0 = returnFunc(ctx, tpl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPermissionTemplateInterface_UpdatePermissionTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePermissionTemplate'
type MockPermissionTemplateInterface_UpdatePermissionTemplate_Call struct {
	*mock.Call
}

// UpdatePermissionTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - tpl *sonar.PermissionTemplate
func (_e *MockPermissionTemplateInterface_Expecter) UpdatePermissionTemplate(ctx interface{}, tpl interface{}) *MockPermissionTemplateInterface_UpdatePermissionTemplate_Call {
	return &MockPermissionTemplateInterface_UpdatePermissionTemplate_Call{Call: _e.mock.On("UpdatePermissionTemplate", ctx, tpl)}
}

func (_c *MockPermissionTemplateInterface_UpdatePermissionTemplate_Call) Run(run func(ctx context.Context, tpl *sonar.PermissionTemplate)) *MockPermissionTemplateInterface_UpdatePermissionTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sonar.PermissionTemplate
		if args[1] != nil {
			arg1 = args[1].(*sonar.PermissionTemplate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPermissionTemplateInterface_UpdatePermissionTemplate_Call) Return(err error) *MockPermissionTemplateInterface_UpdatePermissionTemplate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPermissionTemplateInterface_UpdatePermissionTemplate_Call) RunAndReturn(run func(ctx context.Context, tpl *sonar.PermissionTemplate) error) *MockPermissionTemplateInterface_UpdatePermissionTemplate_Call {
	_c.Call.Return(run)
	return _c
}
