// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/epam/edp-sonar-operator/pkg/client/sonar"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProjectInterface creates a new instance of MockProjectInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectInterface {
	mock := &MockProjectInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProjectInterface is an autogenerated mock type for the ProjectInterface type
type MockProjectInterface struct {
	mock.Mock
}

type MockProjectInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectInterface) EXPECT() *MockProjectInterface_Expecter {
	return &MockProjectInterface_Expecter{mock: &_m.Mock}
}

// CreateProject provides a mock function for the type MockProjectInterface
func (_mock *MockProjectInterface) CreateProject(ctx context.Context, project *sonar.Project) error {
	ret := _mock.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for CreateProject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sonar.Project) error); ok {
		r0 = returnFunc(ctx, project)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProjectInterface_CreateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProject'
type MockProjectInterface_CreateProject_Call struct {
	*mock.Call
}

// CreateProject is a helper method to define mock.On call
//   - ctx context.Context
//   - project *sonar.Project
func (_e *MockProjectInterface_Expecter) CreateProject(ctx interface{}, project interface{}) *MockProjectInterface_CreateProject_Call {
	return &MockProjectInterface_CreateProject_Call{Call: _e.mock.On("CreateProject", ctx, project)}
}

func (_c *MockProjectInterface_CreateProject_Call) Run(run func(ctx context.Context, project *sonar.Project)) *MockProjectInterface_CreateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sonar.Project
		if args[1] != nil {
			arg1 = args[1].(*sonar.Project)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectInterface_CreateProject_Call) Return(err error) *MockProjectInterface_CreateProject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProjectInterface_CreateProject_Call) RunAndReturn(run func(ctx context.Context, project *sonar.Project) error) *MockProjectInterface_CreateProject_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProject provides a mock function for the type MockProjectInterface
func (_mock *MockProjectInterface) DeleteProject(ctx context.Context, projectKey string) error {
	ret := _mock.Called(ctx, projectKey)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, projectKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProjectInterface_DeleteProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProject'
type MockProjectInterface_DeleteProject_Call struct {
	*mock.Call
}

// DeleteProject is a helper method to define mock.On call
//   - ctx context.Context
//   - projectKey string
func (_e *MockProjectInterface_Expecter) DeleteProject(ctx interface{}, projectKey interface{}) *MockProjectInterface_DeleteProject_Call {
	return &MockProjectInterface_DeleteProject_Call{Call: _e.mock.On("DeleteProject", ctx, projectKey)}
}

func (_c *MockProjectInterface_DeleteProject_Call) Run(run func(ctx context.Context, projectKey string)) *MockProjectInterface_DeleteProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectInterface_DeleteProject_Call) Return(err error) *MockProjectInterface_DeleteProject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProjectInterface_DeleteProject_Call) RunAndReturn(run func(ctx context.Context, projectKey string) error) *MockProjectInterface_DeleteProject_Call {
	_c.Call.Return(run)
	return _c
}

// GetProject provides a mock function for the type MockProjectInterface
func (_mock *MockProjectInterface) GetProject(ctx context.Context, projectKey string) (*sonar.Project, error) {
	ret := _mock.Called(ctx, projectKey)

	if len(ret) == 0 {
		panic("no return value specified for GetProject")
	}

	var r0 *sonar.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*sonar.Project, error)); ok {
		return returnFunc(ctx, projectKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *sonar.Project); ok {
		r0 = returnFunc(ctx, projectKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sonar.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, projectKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectInterface_GetProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProject'
type MockProjectInterface_GetProject_Call struct {
	*mock.Call
}

// GetProject is a helper method to define mock.On call
//   - ctx context.Context
//   - projectKey string
func (_e *MockProjectInterface_Expecter) GetProject(ctx interface{}, projectKey interface{}) *MockProjectInterface_GetProject_Call {
	return &MockProjectInterface_GetProject_Call{Call: _e.mock.On("GetProject", ctx, projectKey)}
}

func (_c *MockProjectInterface_GetProject_Call) Run(run func(ctx context.Context, projectKey string)) *MockProjectInterface_GetProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectInterface_GetProject_Call) Return(project *sonar.Project, err error) *MockProjectInterface_GetProject_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *MockProjectInterface_GetProject_Call) RunAndReturn(run func(ctx context.Context, projectKey string) (*sonar.Project, error)) *MockProjectInterface_GetProject_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProject provides a mock function for the type MockProjectInterface
func (_mock *MockProjectInterface) UpdateProject(ctx context.Context, project *sonar.Project) error {
	ret := _mock.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sonar.Project) error); ok {
		r0 = returnFunc(ctx, project)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProjectInterface_UpdateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProject'
type MockProjectInterface_UpdateProject_Call struct {
	*mock.Call
}

// UpdateProject is a helper method to define mock.On call
//   - ctx context.Context
//   - project *sonar.Project
func (_e *MockProjectInterface_Expecter) UpdateProject(ctx interface{}, project interface{}) *MockProjectInterface_UpdateProject_Call {
	return &MockProjectInterface_UpdateProject_Call{Call: _e.mock.On("UpdateProject", ctx, project)}
}

func (_c *MockProjectInterface_UpdateProject_Call) Run(run func(ctx context.Context, project *sonar.Project)) *MockProjectInterface_UpdateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sonar.Project
		if args[1] != nil {
			arg1 = args[1].(*sonar.Project)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectInterface_UpdateProject_Call) Return(err error) *MockProjectInterface_UpdateProject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProjectInterface_UpdateProject_Call) RunAndReturn(run func(ctx context.Context, project *sonar.Project) error) *MockProjectInterface_UpdateProject_Call {
	_c.Call.Return(run)
	return _c
}
