// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/epam/edp-sonar-operator/pkg/client/sonar"
	mock "github.com/stretchr/testify/mock"
)

// NewMockQualityProfileClient creates a new instance of MockQualityProfileClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQualityProfileClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQualityProfileClient {
	mock := &MockQualityProfileClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQualityProfileClient is an autogenerated mock type for the QualityProfileClient type
type MockQualityProfileClient struct {
	mock.Mock
}

type MockQualityProfileClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQualityProfileClient) EXPECT() *MockQualityProfileClient_Expecter {
	return &MockQualityProfileClient_Expecter{mock: &_m.Mock}
}

// ActivateQualityProfileRule provides a mock function for the type MockQualityProfileClient
func (_mock *MockQualityProfileClient) ActivateQualityProfileRule(ctx context.Context, profileKey string, rule sonar.Rule) error {
	ret := _mock.Called(ctx, profileKey, rule)

	if len(ret) == 0 {
		panic("no return value specified for ActivateQualityProfileRule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, sonar.Rule) error); ok {
		r0 = returnFunc(ctx, profileKey, rule)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQualityProfileClient_ActivateQualityProfileRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActivateQualityProfileRule'
type MockQualityProfileClient_ActivateQualityProfileRule_Call struct {
	*mock.Call
}

// ActivateQualityProfileRule is a helper method to define mock.On call
//   - ctx context.Context
//   - profileKey string
//   - rule sonar.Rule
func (_e *MockQualityProfileClient_Expecter) ActivateQualityProfileRule(ctx interface{}, profileKey interface{}, rule interface{}) *MockQualityProfileClient_ActivateQualityProfileRule_Call {
	return &MockQualityProfileClient_ActivateQualityProfileRule_Call{Call: _e.mock.On("ActivateQualityProfileRule", ctx, profileKey, rule)}
}

func (_c *MockQualityProfileClient_ActivateQualityProfileRule_Call) Run(run func(ctx context.Context, profileKey string, rule sonar.Rule)) *MockQualityProfileClient_ActivateQualityProfileRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 sonar.Rule
		if args[2] != nil {
			arg2 = args[2].(sonar.Rule)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQualityProfileClient_ActivateQualityProfileRule_Call) Return(err error) *MockQualityProfileClient_ActivateQualityProfileRule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQualityProfileClient_ActivateQualityProfileRule_Call) RunAndReturn(run func(ctx context.Context, profileKey string, rule sonar.Rule) error) *MockQualityProfileClient_ActivateQualityProfileRule_Call {
	_c.Call.Return(run)
	return _c
}

// CreateQualityProfile provides a mock function for the type MockQualityProfileClient
func (_mock *MockQualityProfileClient) CreateQualityProfile(ctx context.Context, name string, language string) (*sonar.QualityProfile, error) {
	ret := _mock.Called(ctx, name, language)

	if len(ret) == 0 {
		panic("no return value specified for CreateQualityProfile")
	}

	var r0 *sonar.QualityProfile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*sonar.QualityProfile, error)); ok {
		return returnFunc(ctx, name, language)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *sonar.QualityProfile); ok {
		r0 = returnFunc(ctx, name, language)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sonar.QualityProfile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, name, language)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQualityProfileClient_CreateQualityProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateQualityProfile'
type MockQualityProfileClient_CreateQualityProfile_Call struct {
	*mock.Call
}

// CreateQualityProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - language string
func (_e *MockQualityProfileClient_Expecter) CreateQualityProfile(ctx interface{}, name interface{}, language interface{}) *MockQualityProfileClient_CreateQualityProfile_Call {
	return &MockQualityProfileClient_CreateQualityProfile_Call{Call: _e.mock.On("CreateQualityProfile", ctx, name, language)}
}

func (_c *MockQualityProfileClient_CreateQualityProfile_Call) Run(run func(ctx context.Context, name string, language string)) *MockQualityProfileClient_CreateQualityProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQualityProfileClient_CreateQualityProfile_Call) Return(qualityProfile *sonar.QualityProfile, err error) *MockQualityProfileClient_CreateQualityProfile_Call {
	_c.Call.Return(qualityProfile, err)
	return _c
}

func (_c *MockQualityProfileClient_CreateQualityProfile_Call) RunAndReturn(run func(ctx context.Context, name string, language string) (*sonar.QualityProfile, error)) *MockQualityProfileClient_CreateQualityProfile_Call {
	_c.Call.Return(run)
	return _c
}

// DeactivateQualityProfileRule provides a mock function for the type MockQualityProfileClient
func (_mock *MockQualityProfileClient) DeactivateQualityProfileRule(ctx context.Context, profileKey string, ruleKey string) error {
	ret := _mock.Called(ctx, profileKey, ruleKey)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateQualityProfileRule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, profileKey, ruleKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQualityProfileClient_DeactivateQualityProfileRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeactivateQualityProfileRule'
type MockQualityProfileClient_DeactivateQualityProfileRule_Call struct {
	*mock.Call
}

// DeactivateQualityProfileRule is a helper method to define mock.On call
//   - ctx context.Context
//   - profileKey string
//   - ruleKey string
func (_e *MockQualityProfileClient_Expecter) DeactivateQualityProfileRule(ctx interface{}, profileKey interface{}, ruleKey interface{}) *MockQualityProfileClient_DeactivateQualityProfileRule_Call {
	return &MockQualityProfileClient_DeactivateQualityProfileRule_Call{Call: _e.mock.On("DeactivateQualityProfileRule", ctx, profileKey, ruleKey)}
}

func (_c *MockQualityProfileClient_DeactivateQualityProfileRule_Call) Run(run func(ctx context.Context, profileKey string, ruleKey string)) *MockQualityProfileClient_DeactivateQualityProfileRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQualityProfileClient_DeactivateQualityProfileRule_Call) Return(err error) *MockQualityProfileClient_DeactivateQualityProfileRule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQualityProfileClient_DeactivateQualityProfileRule_Call) RunAndReturn(run func(ctx context.Context, profileKey string, ruleKey string) error) *MockQualityProfileClient_DeactivateQualityProfileRule_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteQualityProfile provides a mock function for the type MockQualityProfileClient
func (_mock *MockQualityProfileClient) DeleteQualityProfile(ctx context.Context, name string, language string) error {
	ret := _mock.Called(ctx, name, language)

	if len(ret) == 0 {
		panic("no return value specified for DeleteQualityProfile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, name, language)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQualityProfileClient_DeleteQualityProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteQualityProfile'
type MockQualityProfileClient_DeleteQualityProfile_Call struct {
	*mock.Call
}

// DeleteQualityProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - language string
func (_e *MockQualityProfileClient_Expecter) DeleteQualityProfile(ctx interface{}, name interface{}, language interface{}) *MockQualityProfileClient_DeleteQualityProfile_Call {
	return &MockQualityProfileClient_DeleteQualityProfile_Call{Call: _e.mock.On("DeleteQualityProfile", ctx, name, language)}
}

func (_c *MockQualityProfileClient_DeleteQualityProfile_Call) Run(run func(ctx context.Context, name string, language string)) *MockQualityProfileClient_DeleteQualityProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQualityProfileClient_DeleteQualityProfile_Call) Return(err error) *MockQualityProfileClient_DeleteQualityProfile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQualityProfileClient_DeleteQualityProfile_Call) RunAndReturn(run func(ctx context.Context, name string, language string) error) *MockQualityProfileClient_DeleteQualityProfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetQualityProfile provides a mock function for the type MockQualityProfileClient
func (_mock *MockQualityProfileClient) GetQualityProfile(ctx context.Context, name string) (*sonar.QualityProfile, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetQualityProfile")
	}

	var r0 *sonar.QualityProfile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*sonar.QualityProfile, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *sonar.QualityProfile); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sonar.QualityProfile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQualityProfileClient_GetQualityProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQualityProfile'
type MockQualityProfileClient_GetQualityProfile_Call struct {
	*mock.Call
}

// GetQualityProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockQualityProfileClient_Expecter) GetQualityProfile(ctx interface{}, name interface{}) *MockQualityProfileClient_GetQualityProfile_Call {
	return &MockQualityProfileClient_GetQualityProfile_Call{Call: _e.mock.On("GetQualityProfile", ctx, name)}
}

func (_c *MockQualityProfileClient_GetQualityProfile_Call) Run(run func(ctx context.Context, name string)) *MockQualityProfileClient_GetQualityProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQualityProfileClient_GetQualityProfile_Call) Return(qualityProfile *sonar.QualityProfile, err error) *MockQualityProfileClient_GetQualityProfile_Call {
	_c.Call.Return(qualityProfile, err)
	return _c
}

func (_c *MockQualityProfileClient_GetQualityProfile_Call) RunAndReturn(run func(ctx context.Context, name string) (*sonar.QualityProfile, error)) *MockQualityProfileClient_GetQualityProfile_Call {
	_c.Call.Return(run)
	return _c
}

// SetAsDefaultQualityProfile provides a mock function for the type MockQualityProfileClient
func (_mock *MockQualityProfileClient) SetAsDefaultQualityProfile(ctx context.Context, name string, language string) error {
	ret := _mock.Called(ctx, name, language)

	if len(ret) == 0 {
		panic("no return value specified for SetAsDefaultQualityProfile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, name, language)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQualityProfileClient_SetAsDefaultQualityProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAsDefaultQualityProfile'
type MockQualityProfileClient_SetAsDefaultQualityProfile_Call struct {
	*mock.Call
}

// SetAsDefaultQualityProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - language string
func (_e *MockQualityProfileClient_Expecter) SetAsDefaultQualityProfile(ctx interface{}, name interface{}, language interface{}) *MockQualityProfileClient_SetAsDefaultQualityProfile_Call {
	return &MockQualityProfileClient_SetAsDefaultQualityProfile_Call{Call: _e.mock.On("SetAsDefaultQualityProfile", ctx, name, language)}
}

func (_c *MockQualityProfileClient_SetAsDefaultQualityProfile_Call) Run(run func(ctx context.Context, name string, language string)) *MockQualityProfileClient_SetAsDefaultQualityProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQualityProfileClient_SetAsDefaultQualityProfile_Call) Return(err error) *MockQualityProfileClient_SetAsDefaultQualityProfile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQualityProfileClient_SetAsDefaultQualityProfile_Call) RunAndReturn(run func(ctx context.Context, name string, language string) error) *MockQualityProfileClient_SetAsDefaultQualityProfile_Call {
	_c.Call.Return(run)
	return _c
}
