// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/epam/edp-sonar-operator/pkg/client/sonar"
	mock "github.com/stretchr/testify/mock"
)

// NewMockQualityGateClient creates a new instance of MockQualityGateClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQualityGateClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQualityGateClient {
	mock := &MockQualityGateClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQualityGateClient is an autogenerated mock type for the QualityGateClient type
type MockQualityGateClient struct {
	mock.Mock
}

type MockQualityGateClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQualityGateClient) EXPECT() *MockQualityGateClient_Expecter {
	return &MockQualityGateClient_Expecter{mock: &_m.Mock}
}

// CreateQualityGate provides a mock function for the type MockQualityGateClient
func (_mock *MockQualityGateClient) CreateQualityGate(ctx context.Context, name string) (*sonar.QualityGate, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateQualityGate")
	}

	var r0 *sonar.QualityGate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*sonar.QualityGate, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *sonar.QualityGate); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sonar.QualityGate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQualityGateClient_CreateQualityGate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateQualityGate'
type MockQualityGateClient_CreateQualityGate_Call struct {
	*mock.Call
}

// CreateQualityGate is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockQualityGateClient_Expecter) CreateQualityGate(ctx interface{}, name interface{}) *MockQualityGateClient_CreateQualityGate_Call {
	return &MockQualityGateClient_CreateQualityGate_Call{Call: _e.mock.On("CreateQualityGate", ctx, name)}
}

func (_c *MockQualityGateClient_CreateQualityGate_Call) Run(run func(ctx context.Context, name string)) *MockQualityGateClient_CreateQualityGate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQualityGateClient_CreateQualityGate_Call) Return(qualityGate *sonar.QualityGate, err error) *MockQualityGateClient_CreateQualityGate_Call {
	_c.Call.Return(qualityGate, err)
	return _c
}

func (_c *MockQualityGateClient_CreateQualityGate_Call) RunAndReturn(run func(ctx context.Context, name string) (*sonar.QualityGate, error)) *MockQualityGateClient_CreateQualityGate_Call {
	_c.Call.Return(run)
	return _c
}

// CreateQualityGateCondition provides a mock function for the type MockQualityGateClient
func (_mock *MockQualityGateClient) CreateQualityGateCondition(ctx context.Context, gate string, condition sonar.QualityGateCondition) error {
	ret := _mock.Called(ctx, gate, condition)

	if len(ret) == 0 {
		panic("no return value specified for CreateQualityGateCondition")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, sonar.QualityGateCondition) error); ok {
		r0 = returnFunc(ctx, gate, condition)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQualityGateClient_CreateQualityGateCondition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateQualityGateCondition'
type MockQualityGateClient_CreateQualityGateCondition_Call struct {
	*mock.Call
}

// CreateQualityGateCondition is a helper method to define mock.On call
//   - ctx context.Context
//   - gate string
//   - condition sonar.QualityGateCondition
func (_e *MockQualityGateClient_Expecter) CreateQualityGateCondition(ctx interface{}, gate interface{}, condition interface{}) *MockQualityGateClient_CreateQualityGateCondition_Call {
	return &MockQualityGateClient_CreateQualityGateCondition_Call{Call: _e.mock.On("CreateQualityGateCondition", ctx, gate, condition)}
}

func (_c *MockQualityGateClient_CreateQualityGateCondition_Call) Run(run func(ctx context.Context, gate string, condition sonar.QualityGateCondition)) *MockQualityGateClient_CreateQualityGateCondition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 sonar.QualityGateCondition
		if args[2] != nil {
			arg2 = args[2].(sonar.QualityGateCondition)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQualityGateClient_CreateQualityGateCondition_Call) Return(err error) *MockQualityGateClient_CreateQualityGateCondition_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQualityGateClient_CreateQualityGateCondition_Call) RunAndReturn(run func(ctx context.Context, gate string, condition sonar.QualityGateCondition) error) *MockQualityGateClient_CreateQualityGateCondition_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteQualityGate provides a mock function for the type MockQualityGateClient
func (_mock *MockQualityGateClient) DeleteQualityGate(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteQualityGate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQualityGateClient_DeleteQualityGate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteQualityGate'
type MockQualityGateClient_DeleteQualityGate_Call struct {
	*mock.Call
}

// DeleteQualityGate is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockQualityGateClient_Expecter) DeleteQualityGate(ctx interface{}, name interface{}) *MockQualityGateClient_DeleteQualityGate_Call {
	return &MockQualityGateClient_DeleteQualityGate_Call{Call: _e.mock.On("DeleteQualityGate", ctx, name)}
}

func (_c *MockQualityGateClient_DeleteQualityGate_Call) Run(run func(ctx context.Context, name string)) *MockQualityGateClient_DeleteQualityGate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQualityGateClient_DeleteQualityGate_Call) Return(err error) *MockQualityGateClient_DeleteQualityGate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQualityGateClient_DeleteQualityGate_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockQualityGateClient_DeleteQualityGate_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteQualityGateCondition provides a mock function for the type MockQualityGateClient
func (_mock *MockQualityGateClient) DeleteQualityGateCondition(ctx context.Context, conditionId string) error {
	ret := _mock.Called(ctx, conditionId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteQualityGateCondition")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, conditionId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQualityGateClient_DeleteQualityGateCondition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteQualityGateCondition'
type MockQualityGateClient_DeleteQualityGateCondition_Call struct {
	*mock.Call
}

// DeleteQualityGateCondition is a helper method to define mock.On call
//   - ctx context.Context
//   - conditionId string
func (_e *MockQualityGateClient_Expecter) DeleteQualityGateCondition(ctx interface{}, conditionId interface{}) *MockQualityGateClient_DeleteQualityGateCondition_Call {
	return &MockQualityGateClient_DeleteQualityGateCondition_Call{Call: _e.mock.On("DeleteQualityGateCondition", ctx, conditionId)}
}

func (_c *MockQualityGateClient_DeleteQualityGateCondition_Call) Run(run func(ctx context.Context, conditionId string)) *MockQualityGateClient_DeleteQualityGateCondition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQualityGateClient_DeleteQualityGateCondition_Call) Return(err error) *MockQualityGateClient_DeleteQualityGateCondition_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQualityGateClient_DeleteQualityGateCondition_Call) RunAndReturn(run func(ctx context.Context, conditionId string) error) *MockQualityGateClient_DeleteQualityGateCondition_Call {
	_c.Call.Return(run)
	return _c
}

// GetQualityGate provides a mock function for the type MockQualityGateClient
func (_mock *MockQualityGateClient) GetQualityGate(ctx context.Context, name string) (*sonar.QualityGate, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetQualityGate")
	}

	var r0 *sonar.QualityGate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*sonar.QualityGate, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *sonar.QualityGate); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sonar.QualityGate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQualityGateClient_GetQualityGate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQualityGate'
type MockQualityGateClient_GetQualityGate_Call struct {
	*mock.Call
}

// GetQualityGate is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockQualityGateClient_Expecter) GetQualityGate(ctx interface{}, name interface{}) *MockQualityGateClient_GetQualityGate_Call {
	return &MockQualityGateClient_GetQualityGate_Call{Call: _e.mock.On("GetQualityGate", ctx, name)}
}

func (_c *MockQualityGateClient_GetQualityGate_Call) Run(run func(ctx context.Context, name string)) *MockQualityGateClient_GetQualityGate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQualityGateClient_GetQualityGate_Call) Return(qualityGate *sonar.QualityGate, err error) *MockQualityGateClient_GetQualityGate_Call {
	_c.Call.Return(qualityGate, err)
	return _c
}

func (_c *MockQualityGateClient_GetQualityGate_Call) RunAndReturn(run func(ctx context.Context, name string) (*sonar.QualityGate, error)) *MockQualityGateClient_GetQualityGate_Call {
	_c.Call.Return(run)
	return _c
}

// SetAsDefaultQualityGate provides a mock function for the type MockQualityGateClient
func (_mock *MockQualityGateClient) SetAsDefaultQualityGate(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for SetAsDefaultQualityGate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQualityGateClient_SetAsDefaultQualityGate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAsDefaultQualityGate'
type MockQualityGateClient_SetAsDefaultQualityGate_Call struct {
	*mock.Call
}

// SetAsDefaultQualityGate is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockQualityGateClient_Expecter) SetAsDefaultQualityGate(ctx interface{}, name interface{}) *MockQualityGateClient_SetAsDefaultQualityGate_Call {
	return &MockQualityGateClient_SetAsDefaultQualityGate_Call{Call: _e.mock.On("SetAsDefaultQualityGate", ctx, name)}
}

func (_c *MockQualityGateClient_SetAsDefaultQualityGate_Call) Run(run func(ctx context.Context, name string)) *MockQualityGateClient_SetAsDefaultQualityGate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQualityGateClient_SetAsDefaultQualityGate_Call) Return(err error) *MockQualityGateClient_SetAsDefaultQualityGate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQualityGateClient_SetAsDefaultQualityGate_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockQualityGateClient_SetAsDefaultQualityGate_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateQualityGateCondition provides a mock function for the type MockQualityGateClient
func (_mock *MockQualityGateClient) UpdateQualityGateCondition(ctx context.Context, condition sonar.QualityGateCondition) error {
	ret := _mock.Called(ctx, condition)

	if len(ret) == 0 {
		panic("no return value specified for UpdateQualityGateCondition")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sonar.QualityGateCondition) error); ok {
		r0 = returnFunc(ctx, condition)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQualityGateClient_UpdateQualityGateCondition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateQualityGateCondition'
type MockQualityGateClient_UpdateQualityGateCondition_Call struct {
	*mock.Call
}

// UpdateQualityGateCondition is a helper method to define mock.On call
//   - ctx context.Context
//   - condition sonar.QualityGateCondition
func (_e *MockQualityGateClient_Expecter) UpdateQualityGateCondition(ctx interface{}, condition interface{}) *MockQualityGateClient_UpdateQualityGateCondition_Call {
	return &MockQualityGateClient_UpdateQualityGateCondition_Call{Call: _e.mock.On("UpdateQualityGateCondition", ctx, condition)}
}

func (_c *MockQualityGateClient_UpdateQualityGateCondition_Call) Run(run func(ctx context.Context, condition sonar.QualityGateCondition)) *MockQualityGateClient_UpdateQualityGateCondition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sonar.QualityGateCondition
		if args[1] != nil {
			arg1 = args[1].(sonar.QualityGateCondition)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQualityGateClient_UpdateQualityGateCondition_Call) Return(err error) *MockQualityGateClient_UpdateQualityGateCondition_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQualityGateClient_UpdateQualityGateCondition_Call) RunAndReturn(run func(ctx context.Context, condition sonar.QualityGateCondition) error) *MockQualityGateClient_UpdateQualityGateCondition_Call {
	_c.Call.Return(run)
	return _c
}
