// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/epam/edp-sonar-operator/pkg/client/sonar"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRuleClient creates a new instance of MockRuleClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRuleClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRuleClient {
	mock := &MockRuleClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRuleClient is an autogenerated mock type for the RuleClient type
type MockRuleClient struct {
	mock.Mock
}

type MockRuleClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRuleClient) EXPECT() *MockRuleClient_Expecter {
	return &MockRuleClient_Expecter{mock: &_m.Mock}
}

// GetQualityProfileActiveRules provides a mock function for the type MockRuleClient
func (_mock *MockRuleClient) GetQualityProfileActiveRules(ctx context.Context, profileKey string) ([]sonar.Rule, error) {
	ret := _mock.Called(ctx, profileKey)

	if len(ret) == 0 {
		panic("no return value specified for GetQualityProfileActiveRules")
	}

	var r0 []sonar.Rule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]sonar.Rule, error)); ok {
		return returnFunc(ctx, profileKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []sonar.Rule); ok {
		r0 = returnFunc(ctx, profileKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sonar.Rule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, profileKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRuleClient_GetQualityProfileActiveRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQualityProfileActiveRules'
type MockRuleClient_GetQualityProfileActiveRules_Call struct {
	*mock.Call
}

// GetQualityProfileActiveRules is a helper method to define mock.On call
//   - ctx context.Context
//   - profileKey string
func (_e *MockRuleClient_Expecter) GetQualityProfileActiveRules(ctx interface{}, profileKey interface{}) *MockRuleClient_GetQualityProfileActiveRules_Call {
	return &MockRuleClient_GetQualityProfileActiveRules_Call{Call: _e.mock.On("GetQualityProfileActiveRules", ctx, profileKey)}
}

func (_c *MockRuleClient_GetQualityProfileActiveRules_Call) Run(run func(ctx context.Context, profileKey string)) *MockRuleClient_GetQualityProfileActiveRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRuleClient_GetQualityProfileActiveRules_Call) Return(rules []sonar.Rule, err error) *MockRuleClient_GetQualityProfileActiveRules_Call {
	_c.Call.Return(rules, err)
	return _c
}

func (_c *MockRuleClient_GetQualityProfileActiveRules_Call) RunAndReturn(run func(ctx context.Context, profileKey string) ([]sonar.Rule, error)) *MockRuleClient_GetQualityProfileActiveRules_Call {
	_c.Call.Return(run)
	return _c
}
