// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net/url"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSettings creates a new instance of MockSettings. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSettings(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSettings {
	mock := &MockSettings{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSettings is an autogenerated mock type for the Settings type
type MockSettings struct {
	mock.Mock
}

type MockSettings_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSettings) EXPECT() *MockSettings_Expecter {
	return &MockSettings_Expecter{mock: &_m.Mock}
}

// ResetSettings provides a mock function for the type MockSettings
func (_mock *MockSettings) ResetSettings(ctx context.Context, settingsKeys []string) error {
	ret := _mock.Called(ctx, settingsKeys)

	if len(ret) == 0 {
		panic("no return value specified for ResetSettings")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, settingsKeys)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSettings_ResetSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetSettings'
type MockSettings_ResetSettings_Call struct {
	*mock.Call
}

// ResetSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - settingsKeys []string
func (_e *MockSettings_Expecter) ResetSettings(ctx interface{}, settingsKeys interface{}) *MockSettings_ResetSettings_Call {
	return &MockSettings_ResetSettings_Call{Call: _e.mock.On("ResetSettings", ctx, settingsKeys)}
}

func (_c *MockSettings_ResetSettings_Call) Run(run func(ctx context.Context, settingsKeys []string)) *MockSettings_ResetSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSettings_ResetSettings_Call) Return(err error) *MockSettings_ResetSettings_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSettings_ResetSettings_Call) RunAndReturn(run func(ctx context.Context, settingsKeys []string) error) *MockSettings_ResetSettings_Call {
	_c.Call.Return(run)
	return _c
}

// SetSetting provides a mock function for the type MockSettings
func (_mock *MockSettings) SetSetting(ctx context.Context, setting url.Values) error {
	ret := _mock.Called(ctx, setting)

	if len(ret) == 0 {
		panic("no return value specified for SetSetting")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, url.Values) error); ok {
		r0 = returnFunc(ctx, setting)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSettings_SetSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSetting'
type MockSettings_SetSetting_Call struct {
	*mock.Call
}

// SetSetting is a helper method to define mock.On call
//   - ctx context.Context
//   - setting url.Values
func (_e *MockSettings_Expecter) SetSetting(ctx interface{}, setting interface{}) *MockSettings_SetSetting_Call {
	return &MockSettings_SetSetting_Call{Call: _e.mock.On("SetSetting", ctx, setting)}
}

func (_c *MockSettings_SetSetting_Call) Run(run func(ctx context.Context, setting url.Values)) *MockSettings_SetSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 url.Values
		if args[1] != nil {
			arg1 = args[1].(url.Values)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSettings_SetSetting_Call) Return(err error) *MockSettings_SetSetting_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSettings_SetSetting_Call) RunAndReturn(run func(ctx context.Context, setting url.Values) error) *MockSettings_SetSetting_Call {
	_c.Call.Return(run)
	return _c
}
