// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/epam/edp-sonar-operator/pkg/client/sonar"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSystem creates a new instance of MockSystem. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSystem(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSystem {
	mock := &MockSystem{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSystem is an autogenerated mock type for the System type
type MockSystem struct {
	mock.Mock
}

type MockSystem_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSystem) EXPECT() *MockSystem_Expecter {
	return &MockSystem_Expecter{mock: &_m.Mock}
}

// Health provides a mock function for the type MockSystem
func (_mock *MockSystem) Health(ctx context.Context) (*sonar.SystemHealth, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Health")
	}

	var r0 *sonar.SystemHealth
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*sonar.SystemHealth, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *sonar.SystemHealth); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sonar.SystemHealth)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSystem_Health_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Health'
type MockSystem_Health_Call struct {
	*mock.Call
}

// Health is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSystem_Expecter) Health(ctx interface{}) *MockSystem_Health_Call {
	return &MockSystem_Health_Call{Call: _e.mock.On("Health", ctx)}
}

func (_c *MockSystem_Health_Call) Run(run func(ctx context.Context)) *MockSystem_Health_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSystem_Health_Call) Return(systemHealth *sonar.SystemHealth, err error) *MockSystem_Health_Call {
	_c.Call.Return(systemHealth, err)
	return _c
}

func (_c *MockSystem_Health_Call) RunAndReturn(run func(ctx context.Context) (*sonar.SystemHealth, error)) *MockSystem_Health_Call {
	_c.Call.Return(run)
	return _c
}
