// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/epam/edp-sonar-operator/pkg/client/sonar"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserInterface creates a new instance of MockUserInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserInterface {
	mock := &MockUserInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserInterface is an autogenerated mock type for the UserInterface type
type MockUserInterface struct {
	mock.Mock
}

type MockUserInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserInterface) EXPECT() *MockUserInterface_Expecter {
	return &MockUserInterface_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockUserInterface
func (_mock *MockUserInterface) CreateUser(ctx context.Context, u *sonar.User) error {
	ret := _mock.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sonar.User) error); ok {
		r0 = returnFunc(ctx, u)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserInterface_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserInterface_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - u *sonar.User
func (_e *MockUserInterface_Expecter) CreateUser(ctx interface{}, u interface{}) *MockUserInterface_CreateUser_Call {
	return &MockUserInterface_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, u)}
}

func (_c *MockUserInterface_CreateUser_Call) Run(run func(ctx context.Context, u *sonar.User)) *MockUserInterface_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sonar.User
		if args[1] != nil {
			arg1 = args[1].(*sonar.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserInterface_CreateUser_Call) Return(err error) *MockUserInterface_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserInterface_CreateUser_Call) RunAndReturn(run func(ctx context.Context, u *sonar.User) error) *MockUserInterface_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeactivateUser provides a mock function for the type MockUserInterface
func (_mock *MockUserInterface) DeactivateUser(ctx context.Context, userLogin string) error {
	ret := _mock.Called(ctx, userLogin)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userLogin)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserInterface_DeactivateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeactivateUser'
type MockUserInterface_DeactivateUser_Call struct {
	*mock.Call
}

// DeactivateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userLogin string
func (_e *MockUserInterface_Expecter) DeactivateUser(ctx interface{}, userLogin interface{}) *MockUserInterface_DeactivateUser_Call {
	return &MockUserInterface_DeactivateUser_Call{Call: _e.mock.On("DeactivateUser", ctx, userLogin)}
}

func (_c *MockUserInterface_DeactivateUser_Call) Run(run func(ctx context.Context, userLogin string)) *MockUserInterface_DeactivateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserInterface_DeactivateUser_Call) Return(err error) *MockUserInterface_DeactivateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserInterface_DeactivateUser_Call) RunAndReturn(run func(ctx context.Context, userLogin string) error) *MockUserInterface_DeactivateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateUserToken provides a mock function for the type MockUserInterface
func (_mock *MockUserInterface) GenerateUserToken(userName string) (*string, error) {
	ret := _mock.Called(userName)

	if len(ret) == 0 {
		panic("no return value specified for GenerateUserToken")
	}

	var r0 *string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*string, error)); ok {
		return returnFunc(userName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *string); ok {
		r0 = returnFunc(userName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(userName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserInterface_GenerateUserToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateUserToken'
type MockUserInterface_GenerateUserToken_Call struct {
	*mock.Call
}

// GenerateUserToken is a helper method to define mock.On call
//   - userName string
func (_e *MockUserInterface_Expecter) GenerateUserToken(userName interface{}) *MockUserInterface_GenerateUserToken_Call {
	return &MockUserInterface_GenerateUserToken_Call{Call: _e.mock.On("GenerateUserToken", userName)}
}

func (_c *MockUserInterface_GenerateUserToken_Call) Run(run func(userName string)) *MockUserInterface_GenerateUserToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserInterface_GenerateUserToken_Call) Return(s *string, err error) *MockUserInterface_GenerateUserToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUserInterface_GenerateUserToken_Call) RunAndReturn(run func(userName string) (*string, error)) *MockUserInterface_GenerateUserToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByLogin provides a mock function for the type MockUserInterface
func (_mock *MockUserInterface) GetUserByLogin(ctx context.Context, userLogin string) (*sonar.User, error) {
	ret := _mock.Called(ctx, userLogin)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByLogin")
	}

	var r0 *sonar.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*sonar.User, error)); ok {
		return returnFunc(ctx, userLogin)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *sonar.User); ok {
		r0 = returnFunc(ctx, userLogin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sonar.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userLogin)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserInterface_GetUserByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByLogin'
type MockUserInterface_GetUserByLogin_Call struct {
	*mock.Call
}

// GetUserByLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - userLogin string
func (_e *MockUserInterface_Expecter) GetUserByLogin(ctx interface{}, userLogin interface{}) *MockUserInterface_GetUserByLogin_Call {
	return &MockUserInterface_GetUserByLogin_Call{Call: _e.mock.On("GetUserByLogin", ctx, userLogin)}
}

func (_c *MockUserInterface_GetUserByLogin_Call) Run(run func(ctx context.Context, userLogin string)) *MockUserInterface_GetUserByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserInterface_GetUserByLogin_Call) Return(user *sonar.User, err error) *MockUserInterface_GetUserByLogin_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserInterface_GetUserByLogin_Call) RunAndReturn(run func(ctx context.Context, userLogin string) (*sonar.User, error)) *MockUserInterface_GetUserByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserGroups provides a mock function for the type MockUserInterface
func (_mock *MockUserInterface) GetUserGroups(ctx context.Context, userLogin string) ([]sonar.Group, error) {
	ret := _mock.Called(ctx, userLogin)

	if len(ret) == 0 {
		panic("no return value specified for GetUserGroups")
	}

	var r0 []sonar.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]sonar.Group, error)); ok {
		return returnFunc(ctx, userLogin)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []sonar.Group); ok {
		r0 = returnFunc(ctx, userLogin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sonar.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userLogin)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserInterface_GetUserGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserGroups'
type MockUserInterface_GetUserGroups_Call struct {
	*mock.Call
}

// GetUserGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - userLogin string
func (_e *MockUserInterface_Expecter) GetUserGroups(ctx interface{}, userLogin interface{}) *MockUserInterface_GetUserGroups_Call {
	return &MockUserInterface_GetUserGroups_Call{Call: _e.mock.On("GetUserGroups", ctx, userLogin)}
}

func (_c *MockUserInterface_GetUserGroups_Call) Run(run func(ctx context.Context, userLogin string)) *MockUserInterface_GetUserGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserInterface_GetUserGroups_Call) Return(groups []sonar.Group, err error) *MockUserInterface_GetUserGroups_Call {
	_c.Call.Return(groups, err)
	return _c
}

func (_c *MockUserInterface_GetUserGroups_Call) RunAndReturn(run func(ctx context.Context, userLogin string) ([]sonar.Group, error)) *MockUserInterface_GetUserGroups_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserToken provides a mock function for the type MockUserInterface
func (_mock *MockUserInterface) GetUserToken(ctx context.Context, userLogin string, tokenName string) (*sonar.UserToken, error) {
	ret := _mock.Called(ctx, userLogin, tokenName)

	if len(ret) == 0 {
		panic("no return value specified for GetUserToken")
	}

	var r0 *sonar.UserToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*sonar.UserToken, error)); ok {
		return returnFunc(ctx, userLogin, tokenName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *sonar.UserToken); ok {
		r0 = returnFunc(ctx, userLogin, tokenName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sonar.UserToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userLogin, tokenName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserInterface_GetUserToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserToken'
type MockUserInterface_GetUserToken_Call struct {
	*mock.Call
}

// GetUserToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userLogin string
//   - tokenName string
func (_e *MockUserInterface_Expecter) GetUserToken(ctx interface{}, userLogin interface{}, tokenName interface{}) *MockUserInterface_GetUserToken_Call {
	return &MockUserInterface_GetUserToken_Call{Call: _e.mock.On("GetUserToken", ctx, userLogin, tokenName)}
}

func (_c *MockUserInterface_GetUserToken_Call) Run(run func(ctx context.Context, userLogin string, tokenName string)) *MockUserInterface_GetUserToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserInterface_GetUserToken_Call) Return(userToken *sonar.UserToken, err error) *MockUserInterface_GetUserToken_Call {
	_c.Call.Return(userToken, err)
	return _c
}

func (_c *MockUserInterface_GetUserToken_Call) RunAndReturn(run func(ctx context.Context, userLogin string, tokenName string) (*sonar.UserToken, error)) *MockUserInterface_GetUserToken_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type MockUserInterface
func (_mock *MockUserInterface) UpdateUser(ctx context.Context, u *sonar.User) error {
	ret := _mock.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sonar.User) error); ok {
		r0 = returnFunc(ctx, u)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserInterface_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUserInterface_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - u *sonar.User
func (_e *MockUserInterface_Expecter) UpdateUser(ctx interface{}, u interface{}) *MockUserInterface_UpdateUser_Call {
	return &MockUserInterface_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, u)}
}

func (_c *MockUserInterface_UpdateUser_Call) Run(run func(ctx context.Context, u *sonar.User)) *MockUserInterface_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sonar.User
		if args[1] != nil {
			arg1 = args[1].(*sonar.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserInterface_UpdateUser_Call) Return(err error) *MockUserInterface_UpdateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserInterface_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, u *sonar.User) error) *MockUserInterface_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
