---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: placeholder
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - edp.epam.com
  resources:
  - sonargroups
  - sonarpermissiontemplates
  - sonarprojects
  - sonarqualitygates
  - sonarqualityprofiles
  - sonars
  - sonarusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - edp.epam.com
  resources:
  - sonargroups/finalizers
  - sonarpermissiontemplates/finalizers
  - sonarprojects/finalizers
  - sonarqualitygates/finalizers
  - sonarqualityprofiles/finalizers
  - sonars/finalizers
  - sonarusers/finalizers
  verbs:
  - update
- apiGroups:
  - edp.epam.com
  resources:
  - sonargroups/status
  - sonarpermissiontemplates/status
  - sonarprojects/status
  - sonarqualitygates/status
  - sonarqualityprofiles/status
  - sonars/status
  - sonarusers/status
  verbs:
  - get
  - patch
  - update
