# permissions for end users to edit sonarqualitygates.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: role
    app.kubernetes.io/managed-by: kustomize
  name: sonarqualitygate-editor-role
rules:
- apiGroups:
  - edp.epam.com
  resources:
  - sonarqualitygates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - edp.epam.com
  resources:
  - sonarqualitygates/status
  verbs:
  - get
