# permissions for end users to view sonargroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: role
    app.kubernetes.io/managed-by: kustomize
  name: sonargroup-viewer-role
rules:
- apiGroups:
  - edp.epam.com
  resources:
  - sonargroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - edp.epam.com
  resources:
  - sonargroups/status
  verbs:
  - get
