# This rule is not used by the project sonar-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to edp.epam.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sonar-operator
    app.kubernetes.io/managed-by: kustomize
  name: sonarproject-viewer-role
rules:
- apiGroups:
  - edp.epam.com
  resources:
  - sonarprojects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - edp.epam.com
  resources:
  - sonarprojects/status
  verbs:
  - get
