apiVersion: edp.epam.com/v1alpha1
kind: SonarPermissionTemplate
metadata:
  labels:
    app.kubernetes.io/name: sonarpermissiontemplate
    app.kubernetes.io/managed-by: kustomize
  name: sonarpermissiontemplate-sample
spec:
  name: edp-default
  description: "EDP permission templates"
  projectKeyPattern: ".+"
  default: true
  groupsPermissions:
    sonar-users:
      - issueadmin
    sonar-developers:
      - scan
  sonarRef:
    name: sonar
