apiVersion: edp.epam.com/v1alpha1
kind: SonarQualityGate
metadata:
  labels:
    app.kubernetes.io/name: sonarqualitygate
    app.kubernetes.io/managed-by: kustomize
  name: sonarqualitygate-sample
spec:
  sonarRef:
    name: sonar
  name: sonarqualitygate-sample
  default: true
  conditions:
    new_duplicated_lines_density:
      error: "1"
      op: GT
