apiVersion: edp.epam.com/v1alpha1
kind: Sonar
metadata:
  labels:
    app.kubernetes.io/name: sonar
    app.kubernetes.io/managed-by: kustomize
  name: sonar-sample
spec:
  secret: "sonar-secret"
  url: https://example.com # example
  defaultPermissionTemplate: "edp-default"
  settings:
    - key: sonar.global.exclusions
      values:
        - "**/*.jsx"
        - "**/*.tsx"
    - key: sonar.issue.ignore.block
      fieldValues:
        beginBlockRegexp: ".*"
        endBlockRegexp: ".*"
    - key: sonar.dbcleaner.hoursBeforeKeepingOnlyOneSnapshotByDay
      value: "20"
