apiVersion: edp.epam.com/v1alpha1
kind: SonarGroup
metadata:
  labels:
    app.kubernetes.io/name: sonargroup
    app.kubernetes.io/managed-by: kustomize
  name: sonargroup-sample
spec:
  name: "sonar-developers"
  description: "Developers"
  permissions:
    - "admin"
  sonarRef:
    name: sonar
