apiVersion: v2
description: A Helm chart for EDP Sonar Operator
home: https://epam.github.io/edp-install/
name: sonar-operator
type: application
version: 2.12.0-SNAPSHOT
appVersion: 2.12.0-SNAPSHOT
icon: https://epam.github.io/edp-install/assets/logo.png
keywords:
  - edp
  - sonarqube
  - gates
  - pipelines
maintainers:
  - name: epmd-edp
    email: SupportEPMD-EDP@epam.com
    url: https://solutionshub.epam.com/solution/epam-delivery-platform
  - name: sergk
    url: https://github.com/SergK
sources:
  - https://github.com/epam/edp-sonar-operator
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "true"
  artifacthub.io/images: |
    - name: sonar-operator:2.11.0
      image: epamedp/sonar-operator:2.11.0
    - name: sonarqube:8.9.9-community
      image: sonarqube:8.9.9-community
    - name: postgres:9.6
      image: postgres:9.6
    - name: epamedp/alpine-wget:1.0.3
      image: epamedp/alpine-wget:1.0.3
    - name: busybox:1.35.0
      image: busybox:1.35.0
    - name: alpine:3.16.1
      image: alpine:3.16.1
  artifacthub.io/operatorCapabilities: Full Lifecycle
  artifacthub.io/crds: |
    - kind: Sonar
      version: v2.edp.epam.com/v1
      name: sonar
      displayName: Sonar
      description: Sonar configuraion with predefined Quility Gates, CI users and Groups
    - kind: SonarGroup
      version: v2.edp.epam.com/v1
      name: sonargroup
      displayName: SonarGroup
      description: Sonar Group Management
    - kind: SonarPermissionTemplate
      version: v2.edp.epam.com/v1
      name: sonarpermissiontemplate
      displayName: SonarPermissionTemplate
      description: Sonar Permission template Management
  artifacthub.io/crdsExamples: |
    - apiVersion: v2.edp.epam.com/v1
      kind: Sonar
      metadata:
        name: sonar
      spec:
        basePath: ''
        defaultPermissionTemplate: edp-default
        edpSpec:
          dnsWildcard: eks-sandbox.com
    - apiVersion: v2.edp.epam.com/v1
      kind: SonarGroup
      metadata:
        name: sonar-developers
      spec:
        sonarOwner: sonar
        name: sonar-developers
        description: "Developers"
    - apiVersion: v2.edp.epam.com/v1
      kind: SonarPermissionTemplate
      metadata:
        name: edp-default
      spec:
        description: EDP permission templates (DO NOT REMOVE)
        groupPermissions:
          - groupName: non-interactive-users
            permissions:
              - user
          - groupName: sonar-administrators
            permissions:
              - admin
              - user
          - groupName: sonar-developers
            permissions:
              - codeviewer
              - issueadmin
              - securityhotspotadmin
              - user
        name: edp-default
        projectKeyPattern: .+
        sonarOwner: sonar
  artifacthub.io/links: |
    - name: EDP Documentation
      url: https://epam.github.io/edp-install/
    - name: EPAM SolutionHub
      url: https://solutionshub.epam.com/solution/epam-delivery-platform
