apiVersion: v2
description: A Helm chart for EDP Sonar Operator
home: https://epam.github.io/edp-install/
name: sonar-operator
type: application
version: 3.1.1
appVersion: 3.1.1
icon: https://epam.github.io/edp-install/assets/logo.png
keywords:
  - edp
  - sonarqube
  - gates
  - pipelines
maintainers:
  - name: epmd-edp
    email: SupportEPMD-EDP@epam.com
    url: https://solutionshub.epam.com/solution/epam-delivery-platform
  - name: sergk
    url: https://github.com/SergK
sources:
  - https://github.com/epam/edp-sonar-operator
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "true"
  artifacthub.io/images: |
    - name: sonar-operator:3.0.0
      image: epamedp/sonar-operator:3.0.0
  artifacthub.io/operatorCapabilities: Full Lifecycle
  artifacthub.io/crds: |
    - kind: Sonar
      version: edp.epam.com/v1alpha1
      name: sonar
      displayName: Sonar
      description: Sonar resource for connecting to SonarQube server
    - kind: SonarGroup
      version: edp.epam.com/v1alpha1
      name: sonargroup
      displayName: SonarGroup
      description: Sonar group management
    - kind: SonarPermissionTemplate
      version: edp.epam.com/v1alpha1
      name: sonarpermissiontemplate
      displayName: SonarPermissionTemplate
      description: Sonar permission template management
    - kind: SonarQualityGate
      version: edp.epam.com/v1alpha1
      name: sonarperqualitygate
      displayName: SonarQualityGate
      description: Sonar quality gate management
    - kind: SonarQualityProfile
      version: edp.epam.com/v1alpha1
      name: sonarqualityprofile
      displayName: SonarQualityProfile
      description: Sonar quality profile management
    - kind: SonarUser
      version: edp.epam.com/v1alpha1
      name: sonaruser
      displayName: SonarUser
      description: Sonar user management
  artifacthub.io/crdsExamples: |
    - apiVersion: edp.epam.com/v1alpha1
      kind: Sonar
      metadata:
        name: sonar
      spec:
        url: https://example.com
        secret: sonar-admin
        defaultPermissionTemplate: test
        settings:
          - key: sonar.global.exclusions
            values:
              - "**/*.jsx"
              - "**/*.tsx"
          - key: sonar.issue.ignore.block
            fieldValues:
              beginBlockRegexp: ".*"
              endBlockRegexp: ".*"
          - key: sonar.dbcleaner.hoursBeforeKeepingOnlyOneSnapshotByDay
            value: "20"
    - apiVersion: edp.epam.com/v1alpha1
      kind: SonarGroup
      metadata:
        name: sonar-developers
      spec:
        name: "sonar-developers"
        description: "Developers"
        sonarRef:
          name: sonar
    - apiVersion: edp.epam.com/v1alpha1
      kind: SonarPermissionTemplate
      metadata:
        name: edp-default
      spec:
        name: edp-default
        description: "EDP permission templates"
        projectKeyPattern: ".+"
        default: true
        sonarRef:
          name: sonar
    - apiVersion: edp.epam.com/v1alpha1
      kind: SonarQualityGate
      metadata:
        name: sonarqualitygate-sample
      spec:
        sonarRef:
          name: sonar
        name: sonarqualitygate-sample
        default: true
        conditions:
          new_duplicated_lines_density:
            error: "1"
            op: GT
    - apiVersion: edp.epam.com/v1alpha1
      kind: SonarQualityProfile
      metadata:
        name: sonarqualityprofile-sample
      spec:
        sonarRef:
          name: sonar
        name: sonarqualityprofile-sample
        language: go
        default: true
        rules:
          go:S1151:
            severity: 'MAJOR'
            params: 'max="6"'
    - apiVersion: edp.epam.com/v1alpha1
      kind: SonarUser
      metadata:
        name: sonaruser-sample
      spec:
        secret: sonaruser-secret
        login: sonaruser
        name: sonar user
        email: sonaruser@mail.com
        groups:
          - sonar-administrators
        permissions:
          - scan
        sonarRef:
          name: sonar

  artifacthub.io/links: |
    - name: EDP Documentation
      url: https://epam.github.io/edp-install/
    - name: EPAM SolutionHub
      url: https://solutionshub.epam.com/solution/epam-delivery-platform
