@startuml

skinparam class {
    BackgroundColor #white
	BackgroundColor<<wip>> LightGoldenRodYellow
	BackgroundColor<<tbd>> Khaki
}

package sonar-operator {
    class Sonar {
        -- spec --
        String image
        String version
        String basePath
        []SonarVolumes volumes
        EdpSpec edpSpec
        []LocalObjectReference imagePullSecrets
        -- status --
        Boolean available
        Date lastTimeUpdated
        String status
        String externalUrl
    }

    EdpSpec "1" *-- "1" Sonar
    class EdpSpec <internal> {
        String dnsWildcard
    }

    SonarVolumes "0..*" *-- "1" Sonar
    class SonarVolumes <internal> {
        String name
        String storageClass
        String capacity
    }

    SonarGroup "1" *-- "1" Sonar: sonarOwner
    class SonarGroup {
        String sonarOwner
        String name
        String description
    }

    SonarPermissionTemplate "1" *-- "1" Sonar: sonarOwner
    class SonarPermissionTemplate {
        String sonarOwner
        String name
        String description
        String projectKeyPattern
        GroupPermissions grouppermissions
    }

    SonarPermissionTemplate "1" --* "1..*" GroupPermissions
    class GroupPermissions <internal> {
        String groupName
        Permissions permissions
    }

    GroupPermissions -d-> Permissions : permissions
    enum Permissions {
        admin
        codeviewer
        issueadmin
        scan
        securityhotspotadmin
        user
    }
}

class LocalObjectReference {
    String name
}
Sonar -d-> LocalObjectReference : imagePullSecrets
JenkinsServiceAccount <-d- Sonar : creates sonar-ciuser-token
JenkinsScript <-d- Sonar : creates sonar-jenkins-plugin-config
EDPComponent <-d- Sonar : creates
KeycloakClient <-d- Sonar : creates

@enduml
