{{- if .Values.sonar.deploy -}}
{{ if eq .Values.global.platform "openshift" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: sonar
    {{- include "sonar-operator.labels" . | nindent 4 }}
  {{- with .Values.sonar.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: sonar
spec:
  host: {{if .Values.sonar.basePath}}{{ .Values.global.dnsWildCard }}{{else}}sonar-{{.Values.global.edpName}}.{{.Values.global.dnsWildCard}}{{end}}
  path: {{if .Values.sonar.basePath}}/{{.Values.sonar.basePath}}(/|$)(.*){{else}}/{{end}}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: sonar
    weight: 100
  wildcardPolicy: None
status:
  ingress: []
{{ end }}
{{ end }}
