allowHostDirVolumePlugin: false
allowHostIPC: true
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
allowedCapabilities: []
allowedFlexVolumes: []
apiVersion: security.openshift.io/v1
defaultAddCapabilities: []
fsGroup:
  ranges:
    - max: 999
      min: 999
  type: MustRunAs
groups: []
kind: SecurityContextConstraints
metadata:
  labels:
    app: sonar
  name: sonar-{{.Values.global.edpName}}
priority: 1
readOnlyRootFilesystem: false
requiredDropCapabilities: []
runAsUser:
  type: MustRunAs
  uid: 999
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:{{.Values.global.edpName}}:sonar
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
