{{if .Values.sonar.deploy}}
{{- $storageClassName := .Values.sonar.storage.data.class -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "sonar-data"
  labels:
    app: sonar
    {{- include "sonar-operator.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sonar.storage.data.size }}
{{ if $storageClassName }}
  storageClassName: "{{ $storageClassName }}"
{{ end }}
  volumeMode: Filesystem
{{ end }}
