{{if .Values.sonar.deploy}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sonar
    {{- include "sonar-operator.labels" . | nindent 4 }}
  name: sonar
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: sonar
  sessionAffinity: None
  type: ClusterIP
{{ end }}
