// Code generated by mockery v2.9.4. DO NOT EDIT.

package mock

import (
	mock "github.com/stretchr/testify/mock"

	rest "k8s.io/client-go/rest"

	v1 "github.com/openshift/client-go/apps/clientset/versioned/typed/apps/v1"
)

// OpenshiftPodsStateClient is an autogenerated mock type for the OpenshiftPodsStateClient type
type OpenshiftPodsStateClient struct {
	mock.Mock
}

// DeploymentConfigs provides a mock function with given fields: namespace
func (_m *OpenshiftPodsStateClient) DeploymentConfigs(namespace string) v1.DeploymentConfigInterface {
	ret := _m.Called(namespace)

	var r0 v1.DeploymentConfigInterface
	if rf, ok := ret.Get(0).(func(string) v1.DeploymentConfigInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.DeploymentConfigInterface)
		}
	}

	return r0
}

// RESTClient provides a mock function with given fields:
func (_m *OpenshiftPodsStateClient) RESTClient() rest.Interface {
	ret := _m.Called()

	var r0 rest.Interface
	if rf, ok := ret.Get(0).(func() rest.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rest.Interface)
		}
	}

	return r0
}
