// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ChildInstance is an autogenerated mock type for the ChildInstance type
type ChildInstance struct {
	mock.Mock
}

// GetNamespace provides a mock function with given fields:
func (_m *ChildInstance) GetNamespace() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SonarOwner provides a mock function with given fields:
func (_m *ChildInstance) SonarOwner() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
